#include "InteropTest.h" // This header file is generated by `javac -h . InteropTest.java`
#include <iostream>
#include <jni.h>

extern "C" {
JNIEXPORT jint JNICALL Java_InteropTest_nativeAdd(JNIEnv *env, jobject obj,
                                                  jint a, jint b) {
  return a + b;
}
}

// g++ -shared -o nativeLib.dll InteropTest.cpp -I"$env:JAVA_HOME\include"
// -I"$env:JAVA_HOME\include\win32"