/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InteropTest */

#ifndef _Included_InteropTest
#define _Included_InteropTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InteropTest
 * Method:    nativeAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_InteropTest_nativeAdd
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
